### ISSUE TITLE
Installing fitsio using pip error

### ISSUE THREAD

**Issue by Ashlou** [esheldon/fitsio#107]
Hi,

I'm new to python and I'm sorry if my question is so dumb.
I was trying to install fitsio using pip and even without it but I got the following complsain:
`ValueError: could not configure cfitsio 3370patch`

I would really appreciate any help
Thanks! 

PS.
```
[root@localhost fitsio]# pip install fitsio
Collecting fitsio
  Using cached fitsio-0.9.10.tar.gz
Requirement already satisfied: numpy in /usr/lib64/python2.7/site-packages (from fitsio)
Installing collected packages: fitsio
  Running setup.py install for fitsio ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-MR8nwr/fitsio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u_D_21-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/fitsio
    copying fitsio/util.py -> build/lib.linux-x86_64-2.7/fitsio
    copying fitsio/test.py -> build/lib.linux-x86_64-2.7/fitsio
    copying fitsio/fitslib.py -> build/lib.linux-x86_64-2.7/fitsio
    copying fitsio/__init__.py -> build/lib.linux-x86_64-2.7/fitsio
    running build_ext
    checking build system type... x86_64-unknown-linux-gnu
    checking host system type... x86_64-unknown-linux-gnu
    checking target system type... x86_64-unknown-linux-gnu
    checking for gcc... gcc
    checking whether the C compiler works... no
    configure: error: in `/tmp/pip-build-MR8nwr/fitsio/build/temp.linux-x86_64-2.7/cfitsio3370patch':
    configure: error: C compiler cannot create executables
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-MR8nwr/fitsio/setup.py", line 203, in <module>
        "build_ext": build_ext_subclass,
      File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib64/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-MR8nwr/fitsio/setup.py", line 77, in build_extensions
        RANLIB=self.compiler.ranlib,
      File "/tmp/pip-build-MR8nwr/fitsio/setup.py", line 159, in configure_cfitsio
        raise ValueError("could not configure cfitsio %s" % self.cfitsio_version)
    ValueError: could not configure cfitsio 3370patch
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-MR8nwr/fitsio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-u_D_21-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-MR8nwr/fitsio/
```

**Comment by esheldon** [comment]
It looks like you don't have a C compiler installed

**Comment by Ashlou** [comment]
Hi,
Thanks for your promp reply. I really appreciate it.
I think I have C compiler but I'm not sure if python can see it; for instance see the following where I look up my gcc compiler.

How can I tell the fitsio that I have gcc?

Thanks again!
```
[ashlou@localhost ~]$ gcc
gcc: fatal error: no input files
compilation terminated.
[ashlou@localhost ~]$ gcc --version
gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-2)
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[ashlou@localhost ~]$ which gcc
/usr/bin/gcc
```

**Comment by Ashlou** [comment]
One update: I have also added the path-to-gcc ie. `/usr/bin` to my PATH. Still does not work!

**Comment by esheldon** [comment]
If you are on ubuntu, you might need to do `sudo apt-get install build-essential`

**Comment by Ashlou** [comment]
Thanks!
I'm on Fedora 24. I've tried yum and it didn't work out.

PS.
~~~
[ashlou@localhost ~]$ sudo -s
[sudo] password for ashlou:
[root@localhost ashlou]# yum install build-essential
Redirecting to '/usr/bin/dnf install build-essential' (see 'man yum2dnf')

Last metadata expiration check: 2:43:27 ago on Wed Dec 21 21:18:52 2016.
No package build-essential available.
Error: Unable to find a match.

~~~

**Comment by esheldon** [comment]
I'm not sure how to do this on fedora.

But I think that you have some issue with your system, and this is not related to fitsio itself.

**Comment by Ashlou** [comment]
I couldn't find a way to fix this problem. Thanks anyway though. I do appreciate your support.

**Comment by esheldon** [comment]
did you ever get it working?  On fedora you do `dnf group install 'Development Tools'`

**Comment by WaaallEEE** [comment]
Hi, I have the same issue on mac under conda virtual environments under python 3.6.6. Fitsio installed fine in my other virtual environments with python 3.5.x and below. 

gcc info as seen by my virtual environment:

```
/usr/bin/gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by esheldon** [comment]
Can you all check if this is now working for you?  there were major updates to the pip install, and fitsio  can now also be installed with anaconda.

**Comment by jvines** [comment]
Hi @esheldon , It's not working for me. I get the error `ValueError: could not configure cfitsio 3430`

**Comment by astrom-tom** [comment]
I have the same problem on my Fedora:

gcc version: 9.2.1
python version: 3.7.6

I tried to install the cfitsio by myself (which worked) but did not fix the pip fitsio installation.

**Comment by esheldon** [comment]
are you working with the latest version, released a few days ago?

**Comment by astrom-tom** [comment]
I am using the last version available in pip: fitsio-1.1.1

**Comment by esheldon** [comment]
I don't have these issues any of my systems.

Would it be possible for a fedora user to contribute a travis test that uses fedora rather than the default container for linux?  I'm not sure how one tests with different containers in travis.

In the mean time, is it possible for you to try using anaconda while we find a fix?

**Comment by esheldon** [comment]
To be clear, you can "conda install fitsiio" and it will install a pre-compiled binary, which should avoid this issue.

**Comment by OscarMaireles** [comment]
Try: sudo apt-get install libbz2-dev

**Comment by esheldon** [comment]
he was on fedora, so would have required using yum or some such.
