### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by nuccy** [esheldon/fitsio#138]
I dynamically create the structure of the fits table based on the input data, I have the following data:

`print(data)`
array([(1509126732991, '')], dtype=[('timestamp', '<i8'), ('command', 'S')])

If I then try to write it to fits with:

```
from fitsio import FITS

fits = FITS('test.fits','rw')
fits.write(data)
fits.close()
```

I get "Floating point exception" message which python doesn't catch with try/except, so the application instantly exits.

Could you please clarify how to catch the exception or how to solve the problem. Thanks.

**Comment by nuccy** [comment]
P.S. I use python 2.7 (unfortunately I cannot update to 3, due to system limitation and dependencies).

> numpy.__version__
> '1.11.1'
> fitsio.__version__
> '0.9.11'
>

**Comment by esheldon** [comment]
Thanks for the report, sorry for the long delay replying

this may be somethign to do with scaling of variables.  Can you please post some more information about the bug for future reference?

**Comment by beckermr** [comment]
So here is what is going on here. The data type `'S'` in newer versions of numpy defaults to a zero length string. This is not valid in FITS. @esheldon added some error catching in the python code for this recently. Now on master I get

```bash
(anl) localhost:Desktop Matt$ cat test.py
import fitsio
import numpy as np

data = np.array([(1509126732991, '')], dtype=[('timestamp', '<i8'), ('command', 'S')])

from fitsio import FITS

fits = FITS('test.fits','rw')
fits.write(data)
fits.close()


(anl) localhost:Desktop Matt$ python test.py 
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    fits.write(data)
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.6/site-packages/fitsio/fitslib.py", line 509, in write
    write_bitcols=write_bitcols)
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.6/site-packages/fitsio/fitslib.py", line 812, in write_table
    write_bitcols=write_bitcols)
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.6/site-packages/fitsio/fitslib.py", line 915, in create_table_hdu
    write_bitcols=write_bitcols)
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.6/site-packages/fitsio/fitslib.py", line 3845, in array2tabledef
    name, form, dim = npy2fits(d,table_type=table_type,write_bitcols=write_bitcols)
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.6/site-packages/fitsio/fitslib.py", line 4014, in npy2fits
    name, form, dim = npy_string2fits(d,table_type=table_type)
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.6/site-packages/fitsio/fitslib.py", line 4105, in npy_string2fits
    'got %s for field %s' % (npy_dtype,name))
ValueError: string sizes must be > 0, got S0 for field command
```

I am going to close this issue. The fix on master will appear in v1 in a few weeks hopefully. Feel free to reopen if you are still seeing problems!
