### ISSUE TITLE
Parser crashes on blank header values

### ISSUE THREAD

**Issue by demitri** [esheldon/fitsio#145]
fitsio crashes when a FITS file has no 'value' in the FITS header.

Using this as an example file: <http://irsa.ipac.caltech.edu/ibe/data/spitzer/sha/archive/fallbacks/MIPS005700/MIPS160_ENL.fits>

Read the header:

    import fitsio
    hdu_list = fitsio.FITS("MIPS160_ENL.fits")
    hdu = hdu_list[0]
    hdu.read_header()

Results in this crash:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda/lib/python3.6/site-packages/fitsio/fitslib.py", line 1419, in read_header
    return FITSHDR(self.read_header_list(), convert=True)
  File "/usr/local/anaconda/lib/python3.6/site-packages/fitsio/fitslib.py", line 3913, in __init__
    self.add_record(r, convert=convert)
  File "/usr/local/anaconda/lib/python3.6/site-packages/fitsio/fitslib.py", line 3938, in add_record
    record = FITSRecord(record_in, convert=convert)
  File "/usr/local/anaconda/lib/python3.6/site-packages/fitsio/fitslib.py", line 4247, in __init__
    self.set_record(record, convert=convert)
  File "/usr/local/anaconda/lib/python3.6/site-packages/fitsio/fitslib.py", line 4281, in set_record
    self.set_record(record['card_string'])
  File "/usr/local/anaconda/lib/python3.6/site-packages/fitsio/fitslib.py", line 4269, in set_record
    card=FITSCard(record)
  File "/usr/local/anaconda/lib/python3.6/site-packages/fitsio/fitslib.py", line 4369, in __init__
    self.set_card(card_string)
  File "/usr/local/anaconda/lib/python3.6/site-packages/fitsio/fitslib.py", line 4400, in set_card
    self._set_as_key()
  File "/usr/local/anaconda/lib/python3.6/site-packages/fitsio/fitslib.py", line 4429, in _set_as_key
    res=_fitsio_wrap.parse_card(card_string)
OSError: FITSIO status = 204: keyword value is undefined
```

Yes, the FITS header is invalid (blank values), but it would be nice if fitsio didn't crash.

**Comment by demitri** [comment]
To add a little more detail, this can be worked around to use `read_header_list()` instead which will not crash, but this is not a drop-in replacement and will require writing more code since the return value is different.

Part of the problem is that the program just stops (somewhere there is an `exit()`) and doesn't allow for exception handling.

**Comment by esheldon** [comment]
Sorry I didn't reply to this earlier.  This is probably an easy fix in the FITSHDR code to return `None`.  Is this something you could look into?

**Comment by beckermr** [comment]
I tested this file again on the master branch and this appears to now work properly. I am going to close this issue. The fix should appear in the v1 release, due out in a few weeks.
