### ISSUE TITLE
Array of string in Python3

### ISSUE THREAD

**Issue by londumas** [esheldon/fitsio#149]
I am not sure if this is an issue or something I do wrong.
However I know that the following minimalist code works in Python2 (Python 2.7.11) but not in Python3 (Python 3.6.2 :: Intel Corporation). The version of fitsio is the same: 0.9.11
```
import fitsio
import scipy as sp
out = fitsio.FITS("test.fits.gz",'rw',clobber=True)
d = sp.array(["a","b"])
out.write(d)
out.close()
```
In Python3, I get the following error:
```
TypeError: Unsupported numpy image datatype 19

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bug_fitsio.py", line 8, in <module>
    out.write(d,names=n)
  File "/global/common/software/desi/cori/desiconda/20170920-1.2.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 481, in write
    header=header)
  File "/global/common/software/desi/cori/desiconda/20170920-1.2.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 534, in write_image
    compress=compress, tile_dims=tile_dims)
  File "/global/common/software/desi/cori/desiconda/20170920-1.2.0-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 686, in create_image_hdu
    extver=extver)
SystemError: <built-in method create_image_hdu of _fitsio.FITS object at 0x2b3fc6989930> returned a result with an error set

```

**Comment by esheldon** [comment]
Thanks for the report.

There are two problems here..

First in order to use a list of names (rather than an array with named fields) you must send a *list* of arrays also.

e.g.
```python
arr = sp.array(["a","b"], dtype='S1')
# list of arrays and list of names
d = [ arr ]
n = [ "NAME" ]
out.write(d)
```

But also note how I constructed the array.  I specified the dtype to be string type
```python
arr = sp.array(["a","b"], dtype='S1')
```
In python 3 your version defaults to `U1` which is unicode. Unicode is not supported by FITS.  FITS only supports simple ascii.

**Comment by londumas** [comment]
@esheldon, perfect. Thank you for your help.
