### ISSUE TITLE
pip install fitsio

### ISSUE THREAD

**Issue by astrom-tom** [esheldon/fitsio#165]
Hello,

I ran into an error when installing fitsio for python 3.6.4. When 'pip install fitsio' i get this error:

Collecting fitsio
  Using cached https://files.pythonhosted.org/packages/9c/cb/f52534b71f4d99916723af2994898904015b9a1bf0286a165182d0374bbf/fitsio-0.9.11.tar.gz
Requirement already satisfied: numpy in /home/alien/.local/lib/python3.6/site-packages (from fitsio)
Building wheels for collected packages: fitsio
  Running setup.py bdist_wheel for fitsio ... error
  Failed building wheel for fitsio
  Running setup.py clean for fitsio
Failed to build fitsio
Installing collected packages: fitsio
  Running setup.py install for fitsio ... error
Exception:
Traceback (most recent call last):
  File "/home/alien/Documents/Python_Paranal/Anaconda3/envs/SciOpspy/lib/python3.6/site-packages/pip/compat/__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 58: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alien/Documents/Python_Paranal/Anaconda3/envs/SciOpspy/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/alien/Documents/Python_Paranal/Anaconda3/envs/SciOpspy/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/alien/Documents/Python_Paranal/Anaconda3/envs/SciOpspy/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/alien/Documents/Python_Paranal/Anaconda3/envs/SciOpspy/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/alien/Documents/Python_Paranal/Anaconda3/envs/SciOpspy/lib/python3.6/site-packages/pip/utils/__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "/home/alien/Documents/Python_Paranal/Anaconda3/envs/SciOpspy/lib/python3.6/site-packages/pip/compat/__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 58: invalid start byte

It is worth mentionning that I am in a anaconda environement.

Thank you so much in advance for your help!

**Comment by esheldon** [comment]
should we close this issue since it seems to have gone away?

**Comment by astrom-tom** [comment]
Hi!
Sorry for the delay of my answer. This error still happens with 3.6.4.
I myself updated to 3.6.5 which is fine now but some colleagues still get this problem with 3.6.4.

**Comment by esheldon** [comment]
do you have any idea what changed between 3.6.4 and 3.6.5?  It would help when trying to track this down

**Comment by thecheeseontoast** [comment]
Hello, this is happening for python 3.7 seemingly too. Happened for me on two different systems
