### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by CTugTEZ** [esheldon/fitsio#181]
Hi, try to install fitsio but I take error below. System is Windows 10 x64. I tried pip, setup.py and conda. Pip and setup.py says same error "MSVCCompiler object has no attribute 'compiler'. Conda error is more interesting, it cannot find the package. I tried with navigator too. 

Error by setup.py:

running install
running bdist_egg
running egg_info
writing fitsio.egg-info\PKG-INFO
writing dependency_links to fitsio.egg-info\dependency_links.txt
writing requirements to fitsio.egg-info\requires.txt
writing top-level names to fitsio.egg-info\top_level.txt
reading manifest file 'fitsio.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'fitsio.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
Traceback (most recent call last):
  File ".\setup.py", line 233, in <module>
    "build_ext": build_ext_subclass,
  File "C:\Users\ATASAM\AppData\Roaming\Python\Python36\site-packages\setuptools\__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\ATASAM\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\ATASAM\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\ATASAM\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\ATASAM\AppData\Roaming\Python\Python36\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Users\ATASAM\AppData\Roaming\Python\Python36\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Users\ATASAM\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\ATASAM\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\ATASAM\AppData\Roaming\Python\Python36\site-packages\setuptools\command\bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Users\ATASAM\AppData\Roaming\Python\Python36\site-packages\setuptools\command\bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "C:\Users\ATASAM\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\ATASAM\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\ATASAM\AppData\Roaming\Python\Python36\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Users\ATASAM\Anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Users\ATASAM\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\ATASAM\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\ATASAM\Anaconda3\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File ".\setup.py", line 76, in build_extensions
    CCold=self.compiler.compiler
AttributeError: 'MSVCCompiler' object has no attribute 'compiler'

**Comment by esheldon** [comment]
I'm sorry, I don't have windows to test  fitsio. Does anyone else have access to windows to help?

**Comment by beckermr** [comment]
We could attempt to ship a windows package in conda. I have been avoiding this since it is a can of worms and support on conda-forge is somewhat spotty, but this might help solve the issue.

**Comment by Vagrantin** [comment]
Hello, 
I have also the same issue on Windows platform, looked at the setup.py but couldn’t find anything that would help to workaround this issue…
Any tips are welcome.

**Comment by esheldon** [comment]
Where does this stand now?

Unfortunately we still have no core developers that use windows.  We welcome help from windows experts.
