### ISSUE TITLE
cannot make ascii tables via create_table_hdu

### ISSUE THREAD

**Issue by beckermr** [esheldon/fitsio#187]
This fails:

```python
#!/usr/bin/env python
import fitsio
import numpy as np

fname = 'test.fits'

f = fitsio.FITS(fname, mode='rw', clobber=True)

dtype = [('s1', 'S4'), ('s2', 'S5')]

f.create_table_hdu(dtype=dtype, table_type='ascii')

f[1].write_column(0, np.zeros(10, dtype='S4'))

f.close()

d = fitsio.read(fname)

print(d)
```

Gives:

```bash
Traceback (most recent call last):
  File "test_null_fill.py", line 15, in <module>
    f.create_table_hdu(dtype=dtype, table_type='ascii')
  File "/Users/Matt/miniconda3/envs/anl/lib/python3.6/site-packages/fitsio/fitslib.py", line 968, in create_table_hdu
    extname=extname, extver=extver)
OSError: FITSIO status = 262: unknown TFORM datatype code
Illegal ASCII table TFORMn datatype: '4A'
Failed to write ASCII table header keywords (ffphtb)
```

**Comment by esheldon** [comment]
`table_type` is not being passed to `descr2tabledef` when the dtype is sent.

**Comment by esheldon** [comment]
I pushed a fix for this to the nullstr branch, where we are working testing this functionality

**Comment by esheldon** [comment]
I found a different bug.  Here I write the s2 column with strings of wrong length and get garbage back
```python
import fitsio
import numpy as np

fname = 'test.fits'

with fitsio.FITS(fname, mode='rw', clobber=True) as f:

    dtype = [('s1', 'S4'), ('s2', 'S5')]

    f.create_table_hdu(dtype=dtype, table_type='ascii')

    f[1].write_column('s1', np.zeros(10, dtype='S4'))
    f[1].write_column('s2', np.zeros(10, dtype='S4'))

    f.close()

    d = fitsio.read(fname)

    print('s1:',d['s1'])
    print('s2:',d['s2'])
```
gives
```
s1: [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
s2: [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'A' ' ']
```

**Comment by beckermr** [comment]
There is a section in getcols that trims spaces, but this seems unrelated to changing the null str.

**Comment by esheldon** [comment]
yeah, it looks like we need to add some type checking for `write_column`

**Comment by beckermr** [comment]
Like for the right item length in addition to the right item type?

**Comment by esheldon** [comment]
this is a separate bug

**Comment by esheldon** [comment]
I don't see type checking even, let along string length and array shape checking

**Comment by beckermr** [comment]
Wow ok. Def make a new issue.
