### ISSUE TITLE
test failures for fitsio on both linux and mac osx

### ISSUE THREAD

**Issue by beckermr** [esheldon/fitsio#51]
The master branch of fitsio currently fails the test suite. I tried it on my mac and on linux machines at SLAC. On my mac, it appears that the library is not reading/writing little versus big endian correctly. See the output below. These tests pass in v0.9.7 and so the bug must be in commits after this release. 

```
======================================================================
FAIL: testImageSlice (fitsio.test.TestReadWrite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/ki/beckermr/.local/lib/python2.7/site-packages/fitsio/test.py", line 423, in testImageSlice
    self.compare_array(data[4:12,9:17], rdata, "images")
  File "/u/ki/beckermr/.local/lib/python2.7/site-packages/fitsio/test.py", line 1490, in compare_array
    self.assertEqual(w.size,0,"testing array '%s' dim %d are equal" % (name,i))
AssertionError: testing array 'images' dim 0 are equal

======================================================================
FAIL: testImageWriteRead (fitsio.test.TestReadWrite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/ki/beckermr/.local/lib/python2.7/site-packages/fitsio/test.py", line 302, in testImageWriteRead
    self.compare_array(data, rdata, "images")
  File "/u/ki/beckermr/.local/lib/python2.7/site-packages/fitsio/test.py", line 1490, in compare_array
    self.assertEqual(w.size,0,"testing array '%s' dim %d are equal" % (name,i))
AssertionError: testing array 'images' dim 0 are equal

----------------------------------------------------------------------
Ran 27 tests in 0.725s

FAILED (failures=2)
```

**Comment by esheldon** [comment]
Thanks matt (you can get some sleep too!)

**Comment by esheldon** [comment]
fixed in master
